platform:

  assets:
    kubernetes:
      version: 1.19.6-00
    calico:
      version: 3.15
    istio:
      version: 1.6.3
    nginx:
      version: 0.26.1
    certmanager:
      version: v1.1.0
    heketi:
      version: 9.0.0
    grafana:
      version: 5.2.1
    glusterfs:
      version: 8
    stash:
      version: v0.9.0-rc.6
      catalog:
        version: v0.3.0
      mongodb:
        versions:
          - 4.1
    stashcli:
      version: 0.2.0
    kubedb:
      version: v0.13.0-rc.0
    stern:
      version: 1.11.0

  # Your domain, the platform should be reachable through
  domain: example.com

  # The default Email address to be used by the platform
  email: support@example.com

  # The default administration user account
  admin:
    password: pw%ssp

  # The worker nodes configuration
  workers:
    ram: 4096

  # The storage settings
  storage:
    data:
      size: 300G

  # The network settings
  network:
    ipprefix: 10.88.20

  # The certificate issuer settings
  certissuer:
    # The certificate issuer stage (staging or production)
    default: staging

  # The backup configuration
  backup:
    encryptionkey: tobechanged
    s3:
      access_key: <enter_aws_access_key_here>
      secret_key: <enter_aws_secret_key_here>
    restic:
      url: http://restic-rest-server-url

custom:

  # Custom Kubernetes namespaces to be created upon installation 
  namespaces:
    # - name: my-namespace1
    # - name: my-namespace2
