platform:

  # Your domain, the platform should be reachable through
  domain: example.com

  # The default Email address to be used by the platform
  email: support@example.com

  # The default administration user account
  admin:
    password: pw%ssp

  # The network settings
  network:
    ipprefix: 10.88.20
