- hosts: host
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  become: yes
  tasks:

    # Enable the host firewall

    - name: Deny incoming traffic by default
      ufw:
        default: deny
        direction: incoming

    - name: Allow incoming SSH traffic
      ufw:
        rule: allow
        proto: tcp
        port: '22'

    - name: Enable UFW firewall settings
      ufw:
        state: enabled

    # Install necessary software

    - name: Install KVM
      apt:
        name: qemu-kvm,libvirt-clients,libvirt-daemon-system,bridge-utils,virt-manager,libguestfs-tools,virt-top,sysstat
        state: present
        update_cache: true

    - name: Install further packages
      apt:
        name: apt-transport-https,ca-certificates,curl,software-properties-common,python3-lxml,python3-libvirt
        state: present
        update_cache: true
