- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

    # Install the KubeDB operator

    - name: Wait until the platform has been started completely
      wait_for:
        timeout: 100

    - name: Add the AppsCode Helm repository
      shell: helm repo add appscode https://charts.appscode.com/stable/

    - name: Update the local Helm repository
      shell: helm repo update

    - name: Install the KubeDB operator via it's Helm chart
      shell: "helm install kubedb-operator appscode/kubedb --namespace ssp-base --version {{ platform.assets.kubedb.version }}"

    - name: Wait some seconds for registration of all CRD's
      shell: kubectl -n ssp-base get pod -l release=kubedb-operator
      register: result
      until: (result.stdout | regex_findall("Running") | length) > 0
      retries: 100
      delay: 10

    - name: Wait until the platform has been started completely
      wait_for:
        timeout: 1000

    - name: Install KubeDB catalog of database versions
      shell: |
        helm install kubedb-catalog appscode/kubedb-catalog \
          --version {{ platform.assets.kubedb.version }} \ 
          --namespace kube-system

    # Install the KubeDB command line tool

    - name: Install the KubeDB command line tool
      shell: |
        wget -O kubedb https://github.com/kubedb/cli/releases/download/v{{ platform.assets.kubedb.version }}/kubedb-linux-amd64
        chmod +x kubedb
        mv kubedb /usr/local/bin/
