- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

  - name: Determine the dynamic HTTP port of the Nginx service
    shell: kubectl -n ingress-nginx get svc ingress-nginx -o jsonpath='{.spec.ports[0].nodePort}'
    register: nginx_port_http

  - name: Determine the dynamic HTTPS port of the Nginx service
    shell: kubectl -n ingress-nginx get svc ingress-nginx -o jsonpath='{.spec.ports[1].nodePort}'
    register: nginx_port_https

  - name: Show the ports of the Nginx service
    debug:
      msg: 'Nginx ports: http={{ nginx_port_http.stdout }}, https={{ nginx_port_https.stdout }}'

  - name: Store the NGINX ports
    set_fact:
      nginx_port_http: "{{ nginx_port_http.stdout }}"
      nginx_port_https: "{{ nginx_port_https.stdout }}"

- hosts: host
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

  # Add port forwardings to the Ingress from the outside world

  - name: "Create port forwarding of http host port to node port {{ hostvars['console'].nginx_port_http }}"
    iptables:
      table: nat
      chain: PREROUTING
      protocol: tcp
      destination: '{{ ansible_default_ipv4.address }}'
      destination_port: '80'
      jump: DNAT
      to_destination: "{{ hostvars['kubenode1'].ansible_host }}:{{ hostvars['console'].nginx_port_http }}"

  - name: "Create port forwarding of https host port to node port {{ hostvars['console'].nginx_port_https }}"
    iptables:
      table: nat
      chain: PREROUTING
      protocol: tcp
      destination: '{{ ansible_default_ipv4.address }}'
      destination_port: '443'
      jump: DNAT
      to_destination: "{{ hostvars['kubenode1'].ansible_host }}:{{ hostvars['console'].nginx_port_https }}"

  # Permit port forwarding even on localhost

  - name: "Allow port forwarding of http on localhost from host port to node port {{ hostvars['console'].nginx_port_http }}"
    iptables:
      table: nat
      chain: OUTPUT
      protocol: tcp
      out_interface: lo
      destination_port: '80'
      jump: DNAT
      to_destination: "{{ hostvars['kubenode1'].ansible_host }}:{{ hostvars['console'].nginx_port_http }}"

  - name: "Create port forwarding of https on localhost from host port to node port {{ hostvars['console'].nginx_port_https }}"
    iptables:
      table: nat
      chain: OUTPUT
      protocol: tcp
      out_interface: lo
      destination_port: '443'
      jump: DNAT
      to_destination: "{{ hostvars['kubenode1'].ansible_host }}:{{ hostvars['console'].nginx_port_https }}"
