- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

    # Install Prometheus

    - name: Update the Helm repository
      shell: helm repo update

    - name: Install Prometheus
      shell: helm install prometheus stable/prometheus-operator --namespace ssp-base
