- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

    # Install the Stash operator

    - name: Add the AppsCode Helm repository
      shell: |
        helm repo add appscode https://charts.appscode.com/stable/
        helm repo update

    - name: Install the Stash operator via it's Helm chart
      shell: |
        helm install stash-operator appscode/stash \
          --version {{ platform.assets.stash.version }} \
          --namespace ssp-base

    # Install specific Stash addons

    - name: Wait some time
      wait_for:
        timeout: 240

    - name: Install the Stash MongoDB support
      shell: |
        curl -fsSL https://github.com/stashed/catalog/raw/{{ platform.assets.stash.catalog.version }}/deploy/helm3.sh | bash -s -- --catalog=stash-mongodb

    - name: Install the Stash Postgres support
      shell: |
        curl -fsSL https://github.com/stashed/catalog/raw/{{ platform.assets.stash.catalog.version }}/deploy/helm3.sh | bash -s -- --catalog=stash-postgres

    - name: Install the Stash MySQL support
      shell: |
        curl -fsSL https://github.com/stashed/catalog/raw/{{ platform.assets.stash.catalog.version }}/deploy/helm3.sh | bash -s -- --catalog=stash-mysql

    # Install the Stash command line tools

    - name: Install the Stash kubectl plugin
      shell: |
        wget -O kubectl-stash https://github.com/stashed/cli/releases/download/v{{ platform.assets.stashcli.version }}/kubectl-stash-linux-amd64
        chmod +x kubectl-stash
        mv kubectl-stash /usr/local/bin/
