# Install Longhorn requirements on each data node
- hosts: kubenodes
  become: yes
  vars_files:
  - /opt/mgmt/values-ssp.yaml
  tasks:

  - name: Enforce the ext4 filesystem on the data disk
    shell: mkfs.ext4 /dev/vdb

  - name: Create the longhorn data directory
    file:
      path: /var/lib/longhorn
      state: directory

  - name: Create a permanent mount of the data disk
    mount:
      path: /var/lib/longhorn
      src: /dev/vdb
      fstype: ext4
      state: mounted

  - name: Install iSCSI packages for Longhorn
    apt:
      name: open-iscsi
      state: present

  - name: Install NFS tools for Longhorn
    apt:
      name: nfs-common
      state: present

# Install Longhorn inside the cluster
- hosts: console
  become: yes
  vars_files:
  - /opt/mgmt/values-ssp.yaml
  tasks:

  - name: Install Longhorn
    shell: |
      helm repo add longhorn https://charts.longhorn.io
      helm repo update
      helm install longhorn longhorn/longhorn --namespace ssp \
        --version {{ platform.assets.longhorn.version }} \
        --set defaultSettings.backupTarget=s3://{{ platform.storage.backup.s3.bucket }}@{{ platform.storage.backup.s3.region }}/ \
        --set defaultSettings.backupTargetCredentialSecret=longhorn-backuptarget

  - name: Create an Ingress for the Longhorn UI
    shell: |
      cat <<EOF | kubectl create -f -
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        namespace: ssp
        name: longhorn
        annotations:  
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
      spec:
        tls:
        - hosts:
          - longhorn.ssp.{{ platform.domain }}
          secretName: longhorn-tls
        rules:
        - host: longhorn.ssp.{{ platform.domain }}
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: longhorn-frontend
                  port:
                    number: 80
      EOF

  - name: Create the default storage class
    shell: |
      cat <<EOF | kubectl create -f -
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: default
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      parameters:
        numberOfReplicas: "1"
        staleReplicaTimeout: "2880"
        fromBackup: ""
      EOF

  - name: Create the backup access secret
    shell: |
      cat <<EOF | kubectl create -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: longhorn-backuptarget
        namespace: ssp
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: {{ platform.storage.backup.s3.access_key_id | string | b64encode }}
        AWS_SECRET_ACCESS_KEY: {{ platform.storage.backup.s3.secret_access_key | string | b64encode }}
        AWS_ENDPOINTS: {{ platform.storage.backup.s3.endpoints | string | b64encode }}
      EOF
