- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

    # Install Prometheus

    - name: Install Prometheus
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install prometheus prometheus-community/kube-prometheus-stack \
          --namespace ssp-base \
          --values /opt/mgmt/ssp/kubernetes/monitoring/values.yaml \
          --set prometheus.ingress.hosts[0]=prometheus.ssp.{{ platform.domain }} \
          --set prometheus.ingress.tls[0].hosts[0]=prometheus.ssp.{{ platform.domain }} \
          --set alertmanager.ingress.hosts[0]=alertmanager.ssp.{{ platform.domain }} \
          --set alertmanager.ingress.tls[0].hosts[0]=alertmanager.ssp.{{ platform.domain }} \
          --set grafana.ingress.hosts[0]=grafana.ssp.{{ platform.domain }} \
          --set grafana.ingress.tls[0].hosts[0]=grafana.ssp.{{ platform.domain }} \
          --set grafana.ingress.adminPassword={{ platform.admin.password }}
