- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

    # Install the Stash operator

    - name: Add the AppsCode Helm repository
      shell: |
        helm repo add appscode https://charts.appscode.com/stable/
        helm repo update

    - name: Install the Stash operator via it's Helm chart
      shell: |
        helm install stash-operator appscode/stash \
          --version {{ platform.assets.stash.version }} \
          --namespace ssp

    # Install the Stash command line tools

    - name: Install the Stash kubectl plugin
      shell: |
        wget -O kubectl-stash https://github.com/stashed/cli/releases/download/v{{ platform.assets.stashcli.version }}/kubectl-stash-linux-amd64
        chmod +x kubectl-stash
        mv kubectl-stash /usr/local/bin/

    # Install Velero

    - name: Download Velero
      shell: |
        wget -P /tmp https://github.com/vmware-tanzu/velero/releases/download/v{{ platform.assets.velero.version }}/velero-v{{ platform.assets.velero.version }}-linux-amd64.tar.gz
        tar -xf velero-v{{  platform.assets.velero.version}}-linux-amd64.tar.gz -C /opt
        mv /opt/velero-v1.5.2-linux-amd64 /opt/velero
        chown -R sysadm:sysadm /opt/velero

    - name: Install Velero inside the Kubernetes cluster
      shell: |
        /opt/velero/velero install \
          --provider aws \
          --plugins velero/velero-plugin-for-aws:v1.1.0 \
          --bucket trayla \
          --secret-file /opt/mgmt/velero-secret \
          --use-volume-snapshots=true \
          --backup-location-config region=eu-central-1,s3ForcePathStyle="true",s3Url=http://s3.eu-central-1.wasabisys.com/ \
          --snapshot-location-config region=":default-placement" \
          --use-restic
